version: '3'

services:
  dbserver: 
    build:
      context: mysql
    container_name: dbserver
    hostname: dbserver
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nodeserver:
    build:
      context: node
    container_name: nodeserver
    hostname: nodeserver
    ports:
      - "3000:8080"
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      - dbserver

  nginx:
    build:
      context: nginx
    container_name: nginx
    hostname: nginx
    depends_on:
      - nodeserver
      - dbserver
    ports:
        - "8080:8080"
    networks:
      - node-network
    restart: always

networks:
  node-network:
    driver: bridge